# Generated by Django 5.1.6 on 2025-03-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razon_Social', models.CharField(max_length=100)),
                ('Tipo_documento', models.CharField(choices=[('C.C.', 'C.C'), ('NIT.', 'NIT.'), ('PAS', 'PAS')], default='NIT', max_length=50)),
                ('Idientificacion', models.IntegerField(unique=True)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.EmailField(max_length=100, unique=True)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fecha_Inicio_Actividad', models.DateField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referencia', models.CharField(max_length=100)),
                ('Talla', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Qty_Disponible', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
                ('Diseno', models.CharField(max_length=100)),
                ('Precio_venta', models.FloatField()),
                ('Descuento', models.FloatField()),
                ('Garantia', models.IntegerField()),
                ('CodigoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.codigo')),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
