# Generated by Django 5.1.6 on 2025-03-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referencia', models.CharField(max_length=100)),
                ('Talla', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Qty_Disponible', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=50)),
                ('Diseno', models.CharField(max_length=100)),
                ('Precio_venta', models.FloatField()),
                ('Descuento', models.FloatField()),
                ('Garantia', models.IntegerField()),
                ('CodigoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.codigo')),
            ],
        ),
    ]
