# Generated by Django 5.1.6 on 2025-03-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='Ingreso_Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.ingresos_producto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='Salida_Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.salidas_producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.stock'),
        ),
    ]
