# Generated by Django 5.1.6 on 2025-03-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='diseños')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='diseno_genero',
        ),
        migrations.AddField(
            model_name='producto',
            name='diseno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Producto.disenoproducto'),
        ),
        migrations.DeleteModel(
            name='GeneroDiseno',
        ),
    ]
