# Generated by Django 5.1.6 on 2025-03-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0002_initial'),
        ('bodega', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='stock',
            name='Salida_Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.salidas_producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.stock'),
        ),
    ]
