# Generated by Django 5.1.6 on 2025-03-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_disenoproducto_remove_producto_diseno_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disenoproducto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='diseno',
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Producto.generoproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='diseno',
            field=models.ManyToManyField(related_name='productos', to='Producto.disenoproducto'),
        ),
    ]
