# Generated by Django 5.1.6 on 2025-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_generoproducto_alter_disenoproducto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GeneroProducto',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='DisenoProducto',
            new_name='Diseno',
        ),
        migrations.RenameModel(
            old_name='CategoriaProducto',
            new_name='Genero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ManyToManyField(related_name='productos', to='Producto.color'),
        ),
    ]
