# Generated by Django 5.1.6 on 2025-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_talla_alter_color_options_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='nombre_en_ingles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
