<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-15 03:28
=======
# Generated by Django 5.1.7 on 2025-03-21 19:58
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
<<<<<<< HEAD
        ('empresas', '0001_initial'),
=======
        ('locales', '0001_initial'),
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cliente')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.facturaventa')),
<<<<<<< HEAD
                ('LocalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.local')),
=======
                ('LocalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local')),
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            ],
        ),
    ]
