# Generated by Django 5.1.6 on 2025-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AportesParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SENA', models.FloatField()),
                ('ICBF', models.FloatField()),
                ('Caja_Compensacion', models.FloatField()),
                ('Aporte_Salud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Aprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salud', models.FloatField()),
                ('Pension', models.FloatField()),
                ('Fondo', models.FloatField()),
                ('Retencion', models.FloatField()),
                ('Otros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auxilio_Transporte', models.FloatField()),
                ('Exonerado_Aportes', models.FloatField()),
                ('Dias', models.IntegerField(unique=True)),
                ('Salario', models.FloatField()),
                ('Horas_Extras', models.IntegerField(unique=True)),
                ('Recargos_Nocturnos', models.IntegerField(unique=True)),
                ('Recargos_Domical', models.IntegerField(unique=True)),
                ('Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_pago', models.DateField(auto_now_add=True)),
                ('Fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('Neto_Pagado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Provisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pension', models.FloatField()),
                ('Salud', models.FloatField()),
                ('Riesgo_Laboral', models.FloatField()),
                ('SENA', models.FloatField()),
                ('ICBF', models.FloatField()),
                ('Caja_Compensacion', models.FloatField()),
                ('Prima', models.FloatField()),
                ('Cesantias', models.FloatField()),
                ('Interes_Cesantias', models.FloatField()),
                ('Vacaciones', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
    ]
