# Generated by Django 5.1.6 on 2025-03-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_rename_rol_cargo_rename_rol_account_cargo_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AportesParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SENA', models.FloatField()),
                ('ICBF', models.FloatField()),
                ('Caja_Compensacion', models.FloatField()),
                ('Aporte_Salud', models.FloatField()),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observaciones', models.CharField(max_length=100)),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('UsuarioiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Observaciones', models.CharField(max_length=100)),
                ('AprobadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.aprobador')),
                ('AreaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('UserResponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('UsuarioiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salud', models.FloatField()),
                ('Pension', models.FloatField()),
                ('Fondo', models.FloatField()),
                ('Retencion', models.FloatField()),
                ('Otros', models.FloatField()),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auxilio_Transporte', models.FloatField()),
                ('Exonerado_Aportes', models.FloatField()),
                ('Dias', models.IntegerField(unique=True)),
                ('Salario', models.FloatField()),
                ('Horas_Extras', models.IntegerField(unique=True)),
                ('Recargos_Nocturnos', models.IntegerField(unique=True)),
                ('Recargos_Domical', models.IntegerField(unique=True)),
                ('Total', models.FloatField()),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_pago', models.DateField(auto_now_add=True)),
                ('Fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('Neto_Pagado', models.FloatField()),
                ('Aportes_ParafiscalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.aportesparafiscal')),
                ('ComprobanteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.comprobante')),
                ('DeduccionesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.deducciones')),
                ('DevengadoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado')),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='comprobante',
            name='NomnaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.nomina'),
        ),
        migrations.CreateModel(
            name='Provisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pension', models.FloatField()),
                ('Salud', models.FloatField()),
                ('Riesgo_Laboral', models.FloatField()),
                ('SENA', models.FloatField()),
                ('ICBF', models.FloatField()),
                ('Caja_Compensacion', models.FloatField()),
                ('Prima', models.FloatField()),
                ('Cesantias', models.FloatField()),
                ('Interes_Cesantias', models.FloatField()),
                ('Vacaciones', models.FloatField()),
                ('Total', models.FloatField()),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='nomina',
            name='ProvisionesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.provisiones'),
        ),
    ]
