# Generated by Django 5.1.6 on 2025-03-01 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aportesparafiscal',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='aprobador',
            name='EmpresaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='aprobador',
            name='UsuarioiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='AprobadorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.aprobador'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='AreaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='EmpresaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='UsuarioiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='deducciones',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='devengado',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='Aportes_ParafiscalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.aportesparafiscal'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='ComprobanteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.comprobante'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='DeduccionesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.deducciones'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='DevengadoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='NomnaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.nomina'),
        ),
        migrations.AddField(
            model_name='provisiones',
            name='EmpresaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='ProvisionesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.provisiones'),
        ),
    ]
