# Generated by Django 5.1.6 on 2025-03-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja_Compensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
