# Generated by Django 5.1.6 on 2025-03-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisiones',
            options={'verbose_name': 'Provision', 'verbose_name_plural': 'Provisiones'},
        ),
    ]
