# Generated by Django 5.1.6 on 2025-03-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_arl_caja_compensacion_eps_pension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportesparafiscal',
            options={'verbose_name': 'AportesParafiscal', 'verbose_name_plural': 'AportesParafiscal'},
        ),
        migrations.AlterModelOptions(
            name='aprobador',
            options={'verbose_name': 'Aprobador', 'verbose_name_plural': 'Aprobador'},
        ),
        migrations.AlterModelOptions(
            name='arl',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterModelOptions(
            name='caja_compensacion',
            options={'verbose_name': 'Caja_Compensacion', 'verbose_name_plural': 'Caja_Compensacion'},
        ),
        migrations.AlterModelOptions(
            name='deducciones',
            options={'verbose_name': 'Deducciones', 'verbose_name_plural': 'Deducciones'},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'verbose_name': 'EPS', 'verbose_name_plural': 'EPS'},
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={'verbose_name': 'Nomina', 'verbose_name_plural': 'Nomina'},
        ),
        migrations.AlterModelOptions(
            name='pension',
            options={'verbose_name': 'Pension', 'verbose_name_plural': 'Pension'},
        ),
        migrations.AlterModelOptions(
            name='provisiones',
            options={'verbose_name': 'Provisiones', 'verbose_name_plural': 'Provisiones'},
        ),
    ]
