# Generated by Django 5.1.6 on 2025-03-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_provisiones_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportesparafiscal',
            options={'verbose_name': 'Aporte ParaFiscal', 'verbose_name_plural': 'Aportes ParaFiscales'},
        ),
    ]
