# Generated by Django 5.1.6 on 2025-03-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_aportesparafiscal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportesparafiscal',
            options={'verbose_name': 'Aporte Parafiscal', 'verbose_name_plural': 'Aportes Parafiscales'},
        ),
    ]
