# Generated by Django 5.1.6 on 2025-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_alter_aportesparafiscal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='neto_pagado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provisiones',
            name='total',
            field=models.FloatField(),
        ),
    ]
