# Generated by Django 5.1.6 on 2025-03-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options_and_more'),
        ('telas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
