# Generated by Django 5.1.6 on 2025-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0004_rollotela_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
