# Generated by Django 5.1.6 on 2025-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0005_alter_rollotela_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollotela',
            name='fecha_registro',
        ),
    ]
