# Generated by Django 5.1.6 on 2025-03-12 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0006_remove_rollotela_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollotela',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
