# Generated by Django 5.1.6 on 2025-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0007_rollotela_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
