# Generated by Django 5.1.6 on 2025-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0009_alter_ordenproduccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
