# Generated by Django 5.1.6 on 2025-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0012_alter_ordenproduccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto'), ('Acabado', 'Acabado')], default='Completo', max_length=50),
        ),
    ]
