# Generated by Django 5.1.6 on 2025-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0013_alter_rollotela_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto'), ('Agotado', 'Agotado')], default='Completo', max_length=50),
        ),
    ]
