# Generated by Django 5.1.6 on 2025-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0014_alter_rollotela_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallacorte',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2),
        ),
    ]
