# Generated by Django 5.1.6 on 2025-03-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0015_alter_tallacorte_talla'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentesTela',
            new_name='ComponenteTela',
        ),
    ]
