# Generated by Django 5.1.6 on 2025-03-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0016_rename_componentestela_componentetela'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponenteTela',
            new_name='ComponenteCorte',
        ),
    ]
