# Generated by Django 5.1.6 on 2025-03-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='rol',
            new_name='cargo',
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('nit', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fecha_inicio_actividad', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empresa')),
            ],
        ),
    ]
