# Generated by Django 5.1.6 on 2025-03-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('semidark', 'Semi Dark'), ('minimal', 'Minimal')], default='semidark', max_length=20)),
                ('color_encabezado', models.CharField(default='headercolor1', max_length=20)),
                ('color_sidebar', models.CharField(default='sidebarcolor1', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
