# Generated by Django 5.1.6 on 2025-03-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Horario', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField(unique=True)),
                ('Direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='Salidas_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uso_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Observaciones_Destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('ProveedorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.proveedor')),
            ],
        ),
    ]
