<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-15 03:28
=======
# Generated by Django 5.1.7 on 2025-03-21 19:58
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Ingresos_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
=======
            name='IngresoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uso_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Observaciones_Destino', models.CharField(max_length=100)),
=======
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('observaciones_destino', models.CharField(max_length=255)),
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            ],
        ),
    ]
