<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-15 03:28
=======
# Generated by Django 5.1.7 on 2025-03-21 19:58
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='ingresos_insumo',
            name='ProveedorID',
=======
            model_name='ingresoinsumo',
            name='proveedor',
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
