<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-15 03:28
=======
# Generated by Django 5.1.7 on 2025-03-21 19:58
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0002_initial'),
<<<<<<< HEAD
        ('empresas', '0001_initial'),
=======
        ('locales', '0001_initial'),
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
        ('proveedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='ingresos_insumo',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='ProveedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresos_insumo',
            name='InsumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='LocalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.inventariolocal'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='ProveedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='UserResponsable',
=======
            model_name='ingresoinsumo',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.inventariolocal'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='user_responsable',
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='insumo',
<<<<<<< HEAD
            name='Tipo_insumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipo_insumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='Unidad_MedidaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.unidad_medida'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='InsumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='UserResponsable',
=======
            name='tipo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipoinsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.unidadmedida'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='user_responsable',
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
    ]
