# Generated by Django 5.1.7 on 2025-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingresoproducto',
            name='proveedor',
        ),
    ]
