# Generated by Django 5.1.7 on 2025-03-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0004_productosbodega_remove_ingresoproducto_proveedor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngresoProducto',
            new_name='EntregaCorte',
        ),
        migrations.AddField(
            model_name='productosbodega',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productosbodega',
            name='producto_variante',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bodega_stock', to='Producto.productovariante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entregacorte',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Producto.productovariante'),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='Producto.productovariante'),
        ),
        migrations.AlterField(
            model_name='usoinsumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='Producto.productovariante'),
        ),
    ]
