# Generated by Django 5.1.7 on 2025-03-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0005_rename_ingresoproducto_entregacorte_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosBodega',
            new_name='Stock',
        ),
    ]
