# Generated by Django 5.1.7 on 2025-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_rename_productosbodega_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregacorte',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='salidaproducto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usoinsumo',
            name='observaciones_destino',
        ),
        migrations.AddField(
            model_name='ingresoinsumo',
            name='estado',
            field=models.CharField(choices=[('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Completado', max_length=50),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='uso_destino',
            field=models.CharField(choices=[('Lavado', 'Lavado'), ('Costura', 'Costura'), ('Otros', 'Otros')], default='Lavado', max_length=50),
        ),
    ]
