# Generated by Django 5.1.7 on 2025-03-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_remove_entregacorte_estado_remove_insumo_estado_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaproducto',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoinsumo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Completado', 'Completado')], default='Completado', max_length=50),
        ),
        migrations.CreateModel(
            name='ConfirmacionRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('salida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion', to='bodega.salidaproducto')),
                ('user_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='usuarios.perfilusuario')),
            ],
        ),
    ]
