# Generated by Django 5.1.7 on 2025-03-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_salidaproducto_estado_alter_ingresoinsumo_estado_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionrecepcion',
            name='user_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='usuarios.perfilusuario'),
        ),
    ]
