# Generated by Django 5.1.6 on 2025-03-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compras', '0001_initial'),
        ('Cuentas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='EmpresaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='compras',
            name='Factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.facturacompra'),
        ),
    ]
