<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-15 03:28
=======
# Generated by Django 5.1.7 on 2025-03-21 19:58
>>>>>>> 0143c21 (nuevos cabios en el modulo de bodega)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
    ]
