# Generated by Django 5.1.6 on 2025-03-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Idientificacion',
            new_name='Identificacion',
        ),
    ]
