# Generated by Django 5.1.6 on 2025-03-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
        migrations.RenameModel(
            old_name='DetalleCompras',
            new_name='DetalleCompra',
        ),
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
        migrations.AlterModelOptions(
            name='gastosoperativos',
            options={'verbose_name': 'Gasto Operativo', 'verbose_name_plural': 'GastosOperativos'},
        ),
    ]
