# Generated by Django 5.1.6 on 2025-03-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_rename_compras_compra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastosoperativos',
            options={'verbose_name': 'Gasto Operativo', 'verbose_name_plural': 'Gastos Operativos'},
        ),
    ]
