# Generated by Django 5.1.6 on 2025-03-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
