# Generated by Django 5.1.6 on 2025-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_rename_direccion_local_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
